// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkkghzcpwefwrgacgvdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRra2doemNwd2Vmd3JnYWNndmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjM4NDUsImV4cCI6MjA2OTY5OTg0NX0.gW0PPTbZ0QYP2Jy9lJAiiRP7JZTMJpgO6iLmHftmmI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});